### PR TITLE
Fix Issue #1485 - Model-Key comparison

### LINKED ISSUE #1485: Markers doRebuildAll=false still rebuilds all markers
Not sure if this is related to [#1447](https://github.com/angular-ui/angular-google-maps/issues/1447)

When pushing markers to array, even with doRebuildAll=false specified, markers seem to be rebuilt (assuming since they flash).  When adding 1000's of markers, this gets cumbersome.

This was working with 2.0.12, but seems to no longer work with 2.2.0.  I created a Plunker to compare.  You can simply comment out the 2.2.0 scripts and uncomment the 2.0.12 scripts in the HTML to see the difference.  I added Animation to markers so it's easier to see.  Click "Add Marker" to randomly add a marker and see them re-build.  

[Plunker example](http://plnkr.co/edit/OWQLY8dJHoLr75X6V6yw?p=preview)

Love this library, thanks in advance for the help.  Happy to add to the example if needed.

### PR DESCRIPTION
**Pull request by rcino**
fix(model-key): model-key comparison on objects  

Change model-key to use lodash to compare objects
 - When objects (outside of coords) are compared via ===, the comparison always returns falls, even if objects are same.  Thus, with a false comparison, all markers get marked as needing update, negating doRebuildAll=false.  This fixes false negative on comparison.
 - Add simple examples page with examples controller for issue #1485.
 - Update model-key spec to include a non-coord comparison on models

Closes #1485

### CODE REVIEW

**Comment by cthrax** [comment]
LGTM.

File: src/coffee/directives/api/utils/model-key.coffee [hunk 1]
```diff
@@ -36,7 +36,7 @@ angular.module('uiGmapgoogle-maps.directives.api.utils')
         #compare the rest of the properties that are being watched by scope
         without = _.without(@interface.scopeKeys, 'coords')
         isEqual = _.every without, (k) =>
-          @scopeOrModelVal(scope[k], scope, model1) == @scopeOrModelVal(scope[k], scope, model2)
+          _.isEqual(@scopeOrModelVal(scope[k], scope, model1), @scopeOrModelVal(scope[k], scope, model2))
```
Comment (nmccready) [inline src/coffee/directives/api/utils/model-key.coffee]: This will affect speed for sure. The depth of what is watched should be optional. I know the 4.X branch of lodash is much much faster on this. But this will have a negative effect on users stuck on old lodash,.

**Comment by nmccready** [comment]
The `_.Equals` comparison needs to be made option via the plural directives. Until that is done this will not be merged.

File: src/coffee/directives/api/utils/model-key.coffee (hunk 1 above)
Comment (nmccready) [inline src/coffee/directives/api/utils/model-key.coffee]: @rcino ping

Comment (rcino) [inline src/coffee/directives/api/utils/model-key.coffee]: Yep.  I'll add an option to specify deep object comparison

**Comment by rcino** [comment]
@nmccready Added suggested plurals directive.

**Comment by cthrax** [comment]
@rcino LGTM. Do a build and add the resulting binaries and we can look at getting this merged.

File: example/issue-1485-doRebuildAll.html [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+    <script src="http://cdn.rawgit.com/nmccready/angular-simple-logger/0.0.1/dist/index.js"></script>
+    <script src="../dist/angular-google-maps.js"></script>
+
+    <link href="assets/stylesheets/example.css" rel="stylesheet" type="text/css">
+</head>
+
+<body ng-controller="TestController">
+    {{sites}}
+    <ui-gmap-google-map class="col-sm-12 pad-none" center="map.center" zoom="map.zoom" style="min-height: 600px" draggable="true">
+      <ui-gmap-markers fit="true" deepComparison="true" doRebuildAll="doRebuildAll" models="markers" coords="'coords'" options="'options'" clusteroptions="map.clusterOptions">
```
Comment (nmccready) [inline example/issue-1485-doRebuildAll.html]: @rcino  thank you for an example

File: src/coffee/directives/api/markers.coffee [hunk 3]
```diff
@@ -15,6 +15,7 @@ angular.module("uiGmapgoogle-maps.directives.api")
           type: '=?type' # cluster, spider, default undefined - normal
           typeOptions: '=?typeoptions'
           typeEvents: '=?typeevents'
+          deepComparison: '=?deepcomparison'
```
Comment (nmccready) [inline src/coffee/directives/api/markers.coffee]: Actually you will want to add this scope attribute [here](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee#L37) . That way this gets worked into all plural directives in one shot.

File: src/coffee/directives/api/utils/model-key.coffee [hunk 4]
```diff
@@ -35,8 +35,12 @@ angular.module('uiGmapgoogle-maps.directives.api.utils')
           return isEqual unless isEqual
         #compare the rest of the properties that are being watched by scope
         without = _.without(@interface.scopeKeys, 'coords')
+        console.log("Scope.deepcomparison = " + scope.deepComparison)
```
Comment (nmccready) [inline src/coffee/directives/api/utils/model-key.coffee]: Please use `$log.debug` instead of `console.log` that way the internal log is used and we don't spam a user's app unless they are explicitly debugging.

**Comment by nmccready** [comment]
@rcino almost there a few pointers and this will get merged.

**Comment by rcino** [comment]
@nmccready Yep.  Will take care of these within the next 24 hours.

**Comment by rcino** [comment]
@nmccready Made suggested changes.  Nervous to push binary files that were built by grunt using --force (getting the following warning): 

Warning: Fetching "http://google-maps-utility-library-v3.googlecode.com/svn/tags/keydragzoom/2.0.9/src/keydragzoom.js" failed with HTTP status code 404 Use --force to continue.

**Comment by nmccready** [comment]
@rinco those errors are fixed with latest updates on master. Merge or rebase your code with master. It would actually be easier for you to merge without the build artifacts.

**Comment by nmccready** [comment]
@rcino you should not need to use `--force` anymore. If you rebased or merged in upstream master it should build without errors. 

If your getting errors then there is something wrong with your build where specs or something is failing.

File: src/coffee/directives/api/markers.coffee (hunk 3 above)
Comment (nmccready) [inline src/coffee/directives/api/markers.coffee]: This can be removed here since it is now in plural.coffee

**Comment by rcino** [comment]
@nmccready When I rebased there were way more specs failures (when there weren't any beforehand).  Just haven't had time to figure out what's causing them, since it seems unrelated.  Will try to find time next week

**Comment by nmccready** [comment]
@rcino not sure, I guess I will need to pull in your work manually and try to get this merged locally.

**Comment by nmccready** [comment]
I will try to get to this soon,

**Comment by nmccready** [comment]
I merged it locally and pushed it up @rcino
